"use client";

import { useEffect, useRef } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";

import { Nebula } from "@/components/space/nebula";
import { NebulaClouds } from "@/components/space/nebula-clouds";
import { DeepSkyObjects } from "@/components/space/deep-sky-objects";
import { NamedDeepSky } from "@/components/space/named-deep-sky";
import { CosmicMotes } from "@/components/space/cosmic-motes";

/**
 * Procedural universe environment.
 *
 * No textures. No sky panoramas. No image-based cards. The entire scene
 * is generated by shaders, instanced quads, and GPU points. This is why
 * every layer parallaxes, reads in HDR, and scales to any resolution.
 *
 * Layering (far → near, by radius):
 *
 *   1. Deep-space base color         — #02030a (set on scene.background)
 *   2. Nebula shell (Nebula.tsx)     — camera-centered shader dome at r≈900.
 *                                       Provides subtle galactic-plane glow
 *                                       behind everything so the sky is
 *                                       never flat black.
 *   3. DeepSkyObjects                — ~60 ambient procedural galaxies
 *                                       (world space, r=700..1200), one
 *                                       GPU-instanced draw. The "sky".
 *   4. NamedDeepSky                  — 8 curated landmark anchors
 *                                       (Andromeda, M42, Sgr A*, …) with
 *                                       hover-revealed HUD readouts and
 *                                       3D reticles. The "atlas".
 *   5. NebulaClouds                  — ~12 diffuse procedural nebula
 *                                       patches (world space, r=280..560),
 *                                       parallax with the camera.
 *   6. CosmicMotes                   — ~2400 near-field dust points
 *                                       (r=20..140) — the parallax cue
 *                                       that sells real 3D motion.
 *
 * Items 3–5 live in world space (outside the camera-following group) so
 * they genuinely shift when the camera moves. That's the whole reason
 * this feels like space instead of like a background image.
 */
interface SpaceEnvironmentProps {
  /**
   * Whether to render the named deep-sky HUD layer (Andromeda, M42, …)
   * with its hover readout. Enabled in /explore where users probe the
   * scene, disabled on the home hero where a hoverable HUD would
   * distract from the page's surrounding content.
   */
  showNamedDeepSky?: boolean;
}

export function SpaceEnvironment({ showNamedDeepSky = true }: SpaceEnvironmentProps = {}) {
  const { camera, scene } = useThree();
  const shellRef = useRef<THREE.Group>(null);

  // Deep-space base — a near-black with a very faint blue cast. The Nebula
  // shell, clouds and galaxies layer luminance on top; this is just the
  // void they sit in.
  useEffect(() => {
    const prev = scene.background;
    const color = new THREE.Color("#02030a");
    scene.background = color;
    // Clear any previous envmap. We do lighting with real lights + a touch
    // of hemisphereLight — no sky-IBL required once the background is a
    // flat color.
    const prevEnv = scene.environment;
    scene.environment = null;
    return () => {
      scene.background = prev;
      scene.environment = prevEnv;
    };
  }, [scene]);

  useFrame(() => {
    // The nebula shell follows the camera so the base sky glow never
    // "runs out" no matter how far the user travels. World-space layers
    // (clouds / galaxies / motes) stay put and parallax.
    if (shellRef.current) shellRef.current.position.copy(camera.position);
  });

  return (
    <>
      {/* Camera-following base sky glow (procedural). */}
      <group ref={shellRef}>
        <Nebula />
      </group>

      {/* World-space layers — these are the parallax heroes. */}
      <DeepSkyObjects />
      {showNamedDeepSky ? <NamedDeepSky /> : null}
      <NebulaClouds />
      <CosmicMotes />
    </>
  );
}
